# This is a config for E2B sandbox template.
# You can use template ID (h6ezw57dryh4jakfq100) or template name (codeable-nextjs-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("codeable-nextjs-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("codeable-nextjs-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('codeable-nextjs-test')

team_id = "92b4959f-44df-4083-bdac-451f46a74d69"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "codeable-nextjs-test"
template_id = "h6ezw57dryh4jakfq100"
